def Map properties=[
    artifactName: "${artifact_name}",
    artifactoryProjectName: "${artifactory_project_name}",
    tech: "dotnet6",
    buildArgs: "${build_args}",
    testArgs: "${test_args}",
    ghOrg: "${gh_org}",
    adoIAMRole: "${ado_iam_role}"
    sonarqube: [
        projectKey: "${sq_project_key}"
    ],
    build: [
        dockerargs: "${docker_args}",
        artifactoryPath: "${artifactory_path}",
        workDir: "${work_directory}",
        dockerFile: "${docker_file}"
    ],
    snyk: [
        orgId: "${org_id}"
    ]
] 
@Library("dso-shared-lib@main") _
def podYaml = libraryResource "podTemplates/dotnetcore6-agent.yaml"
pipeline {
    agent{
        kubernetes {
            yaml podYaml
        }
    }
    stages{
        stage ("init"){
            steps {
                container ("jnlp"){
                    sh "echo init"
 //                       init()
                }
            }
        }
         stage ("dotnet build"){
            steps {
                container ("dotnetcore6"){
                    script{
                        dotnet.build()
                    }
                }
            }
        }
         stage ("dotnet test"){
            steps {
                container ("dotnetcore6"){
                    script{
                        dotnet.test()
                    }
                }
            }
        }
         stage ("sonarqube scan"){
            steps {
                container ("sonarqube"){
                    script{               
                        sonarqube.scan(properties)
                    }
                }
            }
        }
         stage ("snyk"){
            steps {
                container ("snyk"){
                    script{         
                        snyk.snykCodeTest(properties)       
                        snyk.snykTest(properties)
                    }
                }
            }
        }
         stage ("kaniko upload"){
            steps {
                container ("awscli"){
                    script{
                        aws.assumeRole(properties.adoIAMRole)
                    }
                }
                container ("kaniko"){
                    script{
                        kaniko.push(properties)
                    }
                }
            }
        }
         stage ("jfrog xray"){
            steps {
                container ("jfrog"){
                    script{               
                        jfrog.jfrogXray(properties)
                    }
                }
            }
        }
    }
    post {
    success {
        script{
            notification.success(properties)

            // notify Slack on success
            slackSend(channel: '#cms-devops-jenkins-slack-notifications', message: "SUCCESS: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' completed successfully. See details: ${env.BUILD_URL}")
        }
    }
    failure {
        script{
            notification.failure(properties)

            // notify Slack on failure
            slackSend(channel: '#cms-devops-jenkins-slack-notifications', message: "FAILURE: Job '${env.JOB_NAME} [${env.BUILD_NUMBER}]' failed. Check it out: ${env.BUILD_URL}")
        }
    } 
}
}