def Map properties=[
    tech: "${tech}",
    slackNotification: "${slack_notification}",
    testArgs: "${test_args}",
    ghOrg: "${gh_org}",
    adoIAMRole: "${ado_iam_role}",
    deploy: [
        artifactHost: "${artifact_host}",
        workDir: "${work_directory}"
    ]
] 
def sharedLibraryBranch
if (env.devopsDebugOverridesSharedLibraryBranch){ sharedLibraryBranch = env.devopsDebugOverridesSharedLibraryBranch }
else { sharedLibraryBranch = "main" }

library "dso-shared-lib@${sharedLibraryBranch}"
def podYaml = libraryResource "podTemplates/helm-agent.yaml"
pipeline {
    agent{
        kubernetes {
            yaml podYaml
        }
    }
    stages{
        stage('GitHub Checkout') {
            steps {
                container("jnlp") {
                    // git branch: 'maven3.8-java17-std', credentialsId: 'git_token', url: 'https://github.com/CMSgov/cmscloud-infra-jenkins-examples.git'
                    checkout scmGit(branches: [[name: "${github_branch}"]], extensions: [], userRemoteConfigs: [[credentialsId: "git_token", url: "${github_repo}"]])
                }
            }
        }
        stage ("Init"){
            steps {
                container ("jnlp"){
                    sh "echo init"
 //                       init()
                }
            }
        }
        stage ("helm deploy") {
            steps {
                container ("jnlp") {
                    sh "echo helm deploy"
                } 
            }
        }
        stage ("Post-deploy maven test") {
            when { expression { tech.contains("maven") }}
            steps {
                container ("maven") {
                    script{ 
                        maven.test(properties.testArgs)
                    }
                }
            }
        }
        stage ("Post-deploy dotnet test") {
            when { expression { tech.contains("dotnet") }}
            steps {
                container ("dotnet") {
                    script {
                        dotnet.test(properties.testArgs)
                    }
                }
            }
        }
        stage ("Post-deploy gradle test") {
            when { expression { tech.contains("gradle") }}
            steps {
                container ("gradle") {
                    script {
                        gradle.gradleTest(properties.testArgs)
                    }
                }
            }
        }
    }
}