def Map properties=[
    artifactName: "${artifact_name}",
    artifactoryProjectName: "${artifactory_project_name}",
    tech: "maven3.8",
    javaVersion: "${java_version}",
    buildArgs: "${build_args}",
    testArgs: "${test_args}",
    packageArgs: "${package_args}",
    ghOrg: "${gh_org}",
    adoIAMRole: "${ado_iam_role}",
    sonarqube: [
        projectKey: "${sq_project_key}"
    ],
    build: [
        dockerargs: "${docker_args}",
        artifactoryPath: "${artifactory_path}",
        workDir: "${work_directory}",
        dockerFile: "${docker_file}"
    ],
    snyk: [
        orgId: "${org_id}"
    ],
    selenium: [
        testUrl: "${selenium_test_url}",
        browser: "${selenium_browser}",
        video: "${selenium_video}",
        credentialsId: "${selenium_credentials_id}",
        mavenConfigFile: "${selenium_maven_config_file}"
    ]
] 
@Library("dso-shared-lib@main") _
def podYaml = libraryResource "podTemplates/maven3.8-java${properties.javaVersion}-agent.yaml"
pipeline {
    agent{
        kubernetes {
            yaml podYaml
        }
    }
    stages{
        stage ("init"){
            steps {
                container ("jnlp"){
                    sh "echo init"
 //                       init()
                }
            }
        }
         stage ("maven compile"){
            steps {
                container ("maven"){
                    script{
                        maven.compile(properties.buildArgs)
                    }
                }
            }
        }
         stage ("maven test"){
            steps {
                container ("maven"){
                    script{
                        maven.test(properties.testArgs)
                    }
                }
            }
        }
        stage ("maven package"){
            steps {
                container ("maven"){
                    script{
                        maven.mvnPackage(properties.packageArgs)
                    }
                }
            }
        }
         stage ("sonarqube scan"){
            steps {
                container ("sonarqube"){
                    script{               
                        sonarqube.scan(properties)
                    }
                }
            }
        }
         stage ("snyk"){
            steps {
                container ("snyk"){
                    script{        
                        snyk.snykCodeTest(properties)        
                        snyk.snykTest(properties)
                    }
                }
            }
        }
        stage ("selenium"){
            steps {
                container ("maven"){
                    script{        
                        selenium.runSeleniumTests(properties)        
                    }
                }
            }
        }
         stage ("kaniko upload"){
            steps {
                container ("awscli"){
                    script{
                        aws.assumeRole(properties.adoIAMRole)
                    }
                 }
                container ("kaniko"){
                    script{
                        kaniko.push(properties)
                    }
                }
            }
        }
         stage ("jfrog xray"){
            steps {
                container ("jfrog"){
                    script{               
                        jfrog.jfrogXray(properties)
                    }
                }
            }
        }
    }
    post {
        success {
            script{
                notification.success(properties)
            }
        }
        failure {
            script{
                notification.failure(properties)
            }
        }
    }
}